// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'Company.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Company _$CompanyFromJson(Map<String, dynamic> json) => Company(
      id: json['id'] as int?,
      companyid: json['companyid'] as int?,
      companyname: json['companyname'] as String?,
      ticker: json['ticker'] as String?,
      price: (json['price'] as num?)?.toDouble(),
      p_l: (json['p_l'] as num?)?.toDouble(),
      dy: (json['dy'] as num?)?.toDouble(),
      p_vp: (json['p_vp'] as num?)?.toDouble(),
      p_ebit: (json['p_ebit'] as num?)?.toDouble(),
      p_ativo: (json['p_ativo'] as num?)?.toDouble(),
      ev_ebit: (json['ev_ebit'] as num?)?.toDouble(),
      margembruta: (json['margembruta'] as num?)?.toDouble(),
      margemebit: (json['margemebit'] as num?)?.toDouble(),
      margemliquida: (json['margemliquida'] as num?)?.toDouble(),
      p_sr: (json['p_sr'] as num?)?.toDouble(),
      p_capitalgiro: (json['p_capitalgiro'] as num?)?.toDouble(),
      p_ativocirculante: (json['p_ativocirculante'] as num?)?.toDouble(),
      giroativos: (json['giroativos'] as num?)?.toDouble(),
      roe: (json['roe'] as num?)?.toDouble(),
      roa: (json['roa'] as num?)?.toDouble(),
      roic: (json['roic'] as num?)?.toDouble(),
      peg_ratio: (json['peg_ratio'] as num?)?.toDouble(),
      dividaliquidapatrimonioliquido:
          (json['dividaliquidapatrimonioliquido'] as num?)?.toDouble(),
      dividaLiquidaebit: (json['dividaLiquidaebit'] as num?)?.toDouble(),
      pl_ativo: (json['pl_ativo'] as num?)?.toDouble(),
      passivo_ativo: (json['passivo_ativo'] as num?)?.toDouble(),
      liquidezcorrente: (json['liquidezcorrente'] as num?)?.toDouble(),
      receitas_cagr5: (json['receitas_cagr5'] as num?)?.toDouble(),
      lucros_cagr5: (json['lucros_cagr5'] as num?)?.toDouble(),
      liquidezmediadiaria: (json['liquidezmediadiaria'] as num?)?.toDouble(),
      vpa: (json['vpa'] as num?)?.toDouble(),
      lpa: (json['lpa'] as num?)?.toDouble(),
      valormercado: (json['valormercado'] as num?)?.toDouble(),
      createdAt: json['createdAt'] == null
          ? null
          : DateTime.parse(json['createdAt'] as String),
      updatedAt: json['updatedAt'] == null
          ? null
          : DateTime.parse(json['updatedAt'] as String),
      segmentid: json['segmentid'] as int?,
      sectorid: json['sectorid'] as int?,
      subsectorid: json['subsectorid'] as int?,
      subsectorname: json['subsectorname'] as String?,
      segmentname: json['segmentname'] as String?,
      sectorname: json['sectorname'] as String?,
      vi: (json['vi'] as num?)?.toDouble(),
      percent_more: (json['percent_more'] as num?)?.toDouble(),
      tagAlong: json['tagAlong'] as String?,
    );

Map<String, dynamic> _$CompanyToJson(Company instance) => <String, dynamic>{
      'id': instance.id,
      'companyid': instance.companyid,
      'companyname': instance.companyname,
      'ticker': instance.ticker,
      'price': instance.price,
      'p_l': instance.p_l,
      'dy': instance.dy,
      'p_vp': instance.p_vp,
      'p_ebit': instance.p_ebit,
      'p_ativo': instance.p_ativo,
      'ev_ebit': instance.ev_ebit,
      'margembruta': instance.margembruta,
      'margemebit': instance.margemebit,
      'margemliquida': instance.margemliquida,
      'p_sr': instance.p_sr,
      'p_capitalgiro': instance.p_capitalgiro,
      'p_ativocirculante': instance.p_ativocirculante,
      'giroativos': instance.giroativos,
      'roe': instance.roe,
      'roa': instance.roa,
      'roic': instance.roic,
      'dividaliquidapatrimonioliquido': instance.dividaliquidapatrimonioliquido,
      'dividaLiquidaebit': instance.dividaLiquidaebit,
      'pl_ativo': instance.pl_ativo,
      'passivo_ativo': instance.passivo_ativo,
      'liquidezcorrente': instance.liquidezcorrente,
      'peg_ratio': instance.peg_ratio,
      'receitas_cagr5': instance.receitas_cagr5,
      'lucros_cagr5': instance.lucros_cagr5,
      'liquidezmediadiaria': instance.liquidezmediadiaria,
      'vpa': instance.vpa,
      'lpa': instance.lpa,
      'valormercado': instance.valormercado,
      'createdAt': instance.createdAt?.toIso8601String(),
      'updatedAt': instance.updatedAt?.toIso8601String(),
      'segmentid': instance.segmentid,
      'sectorid': instance.sectorid,
      'subsectorid': instance.subsectorid,
      'subsectorname': instance.subsectorname,
      'segmentname': instance.segmentname,
      'sectorname': instance.sectorname,
      'vi': instance.vi,
      'percent_more': instance.percent_more,
      'tagAlong': instance.tagAlong,
    };
